/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define RCC_BASE_ADDR			0x40023800UL

#define RCC_CR_REG_OFFSET		0x00UL
#define RCC_CFGR_REG_OFFSET		0x08UL

#define RCC_CFGR_REG_ADDR	(RCC_BASE_ADDR + RCC_REG_OFFSET)
#define RCC_CR_REG_ADDR		(RCC_BASE_ADDR + RCC_CR_REG_OFFSET)

int main(void)
{
	// 1. Enable the HSE clock using HSEON bit
	uint32_t *p_rccCrReg = (uint32_t*)RCC_CR_REG_ADDR;
	uint32_t *p_rccCfgrReg = (uint32_t*)RCC_CFGR_REG_ADDR;

	*p_rccCrReg |= (1 << 16);

	// 2. Wait until HSE clock from the external crystal stabilises
	while ( !(*p_rccCrReg & (1 << 17)) );

	// 3. Switch the system clock to HSE (RCC_CFGR)
	*p_rccCfgrReg &= ~3;
	*p_rccCfgrReg |= 1;

	// 4. Do MC01 settings to measure it

	for(;;);
}
