/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ADC_BASE_ADDR		0x40012000UL
#define RCC_BASE_ADDR		0x40023800UL

#define ADC_CR1_REF_OFFSET	0x04UL
#define RCC_APB2_ENR_OFFSET	0x44UL

#define ADC_CR1_REG_ADDR	(ADC_BASE_ADDR + ADC_CR1_REF_OFFSET)
#define RCC_APB2_ENR_ADDR	(RCC_BASE_ADDR + RCC_APB2_ENR_OFFSET)

int main(void)
{
	uint32_t *p_rccApb2Enr = (uint32_t *) RCC_APB2_ENR_ADDR;
	*p_rccApb2Enr |= (1 << 8);

	// Will not be able to do this until you enable external clock
    uint32_t *p_cr1RegAddr = (uint32_t*) ADC_CR1_REG_ADDR;
    *p_cr1RegAddr |= (1 << 8);

	for(;;);
}
